using BorsaSanitatGUI.Models.Parámetros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BorsaSanitatGUI.Utils
{
    public static class Constantes
    {
        private const string HOST = "https://www2.san.gva.es";
        public const string URL_SITUACIO = $"{HOST}/bolsa/lstSituacionCandidatos.jsp";
        public const string URL_PUNTUACIO = $"{HOST}/bolsa/lstCandidatosListaOperativa.jsp";
        public const string URL_DADES_PERSONALS = $"{HOST}/bolsa/lstDniApellido.jsp";

        public static List<DepartamentoCod> departamentoCod = new List<DepartamentoCod>()
        {
            new DepartamentoCod() { NombreDepartamento = "Alicante", CodigoDepartamento = "ALI"},
            new DepartamentoCod() { NombreDepartamento = "Alcoy", CodigoDepartamento = "ALY"},
            new DepartamentoCod() { NombreDepartamento = "Arnau", CodigoDepartamento = "ARN"},
            new DepartamentoCod() { NombreDepartamento = "Castellon", CodigoDepartamento = "CAS"},
            new DepartamentoCod() { NombreDepartamento = "Clinico", CodigoDepartamento = "CLI"},
            new DepartamentoCod() { NombreDepartamento = "Denia", CodigoDepartamento = "DEN"},
            new DepartamentoCod() { NombreDepartamento = "Elda", CodigoDepartamento = "ELD"},
            new DepartamentoCod() { NombreDepartamento = "Elx", CodigoDepartamento = "ELX"},
            new DepartamentoCod() { NombreDepartamento = "Gandia", CodigoDepartamento = "GAN"},
            new DepartamentoCod() { NombreDepartamento = "General", CodigoDepartamento = "GEN"},
            new DepartamentoCod() { NombreDepartamento = "La Fe", CodigoDepartamento = "LFE"},
            new DepartamentoCod() { NombreDepartamento = "Marina", CodigoDepartamento = "MBA"},
            new DepartamentoCod() { NombreDepartamento = "Orihuela", CodigoDepartamento = "ORI"},
            new DepartamentoCod() { NombreDepartamento = "Peset", CodigoDepartamento = "PES"},
            new DepartamentoCod() { NombreDepartamento = "La Plana", CodigoDepartamento = "PLA"},
            new DepartamentoCod() { NombreDepartamento = "Requena", CodigoDepartamento = "REQ"},
            new DepartamentoCod() { NombreDepartamento = "Ribera", CodigoDepartamento = "RIB"},
            new DepartamentoCod() { NombreDepartamento = "SA", CodigoDepartamento = "SA"},
            new DepartamentoCod() { NombreDepartamento = "Sagunto", CodigoDepartamento = "SAG"},
            new DepartamentoCod() { NombreDepartamento = "SES Castelló", CodigoDepartamento = "SC"},
            new DepartamentoCod() { NombreDepartamento = "Serveis Centrals", CodigoDepartamento = "SCC"},
            new DepartamentoCod() { NombreDepartamento = "S.P. Alacant", CodigoDepartamento = "SPA"},
            new DepartamentoCod() { NombreDepartamento = "S.P. Castelló", CodigoDepartamento = "SPC"},
            new DepartamentoCod() { NombreDepartamento = "S.P. Valencia", CodigoDepartamento = "SPV"},
            new DepartamentoCod() { NombreDepartamento = "S.P. Alcoy", CodigoDepartamento = "SPY"},
            new DepartamentoCod() { NombreDepartamento = "SV", CodigoDepartamento = "SV"},
            new DepartamentoCod() { NombreDepartamento = "Torrevieja", CodigoDepartamento = "TRV"},
            new DepartamentoCod() { NombreDepartamento = "Vinaroz", CodigoDepartamento = "VIN"},
            new DepartamentoCod() { NombreDepartamento = "Xativa", CodigoDepartamento = "XAT"},

        };

        public static List<CategoriaCod> categoriaCod = new List<CategoriaCod>()
        {
            new CategoriaCod() { NombreCategoria ="Enginyer D'Aplicacions I Sistemes", CodigoCategoria = "0001"},
            new CategoriaCod() { NombreCategoria ="Analista Programador I De Sistemes", CodigoCategoria = "0002"},
            new CategoriaCod() { NombreCategoria ="Metge Conductes Addictives", CodigoCategoria = "0004"},
            new CategoriaCod() { NombreCategoria ="Metge Unitat De Curta Estada", CodigoCategoria = "0006"},
            new CategoriaCod() { NombreCategoria ="Metge Unitat De Prevenció Càncer De Mama", CodigoCategoria = "0007"},
            new CategoriaCod() { NombreCategoria ="Metge Unitat Hospitalitzaciò A Domicili", CodigoCategoria = "0008"},
            new CategoriaCod() { NombreCategoria ="Tècnic D'Informatica", CodigoCategoria = "0009"},
            new CategoriaCod() { NombreCategoria ="Metge Documentació Clínica I Admissió", CodigoCategoria = "0010"},
            new CategoriaCod() { NombreCategoria ="Auxiliar Administratiu", CodigoCategoria = "0011"},
            new CategoriaCod() { NombreCategoria ="Tècnic De Manteniment", CodigoCategoria = "0015"},
            new CategoriaCod() { NombreCategoria ="T.E. Medicina Nuclear", CodigoCategoria = "0016"},
            new CategoriaCod() { NombreCategoria ="T.E. Radioteràpia", CodigoCategoria = "0017"},
            new CategoriaCod() { NombreCategoria ="Metge Planificació Familiar", CodigoCategoria = "0018"},
            new CategoriaCod() { NombreCategoria ="Farmacèutic D'Àrea", CodigoCategoria = "0019"},
            new CategoriaCod() { NombreCategoria ="Metge Equip Mòbil", CodigoCategoria = "0020"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Bioquímica Clínica", CodigoCategoria = "0037"},
            new CategoriaCod() { NombreCategoria ="Treballador Social", CodigoCategoria = "0057"},
            new CategoriaCod() { NombreCategoria ="Administratiu", CodigoCategoria = "0087"},
            new CategoriaCod() { NombreCategoria ="Metge De Familia E.A.P.", CodigoCategoria = "0244"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Especialista Obstétrico-Ginecològica", CodigoCategoria = "0246"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Psiquiatria", CodigoCategoria = "0257"},
            new CategoriaCod() { NombreCategoria ="T.E. Laboratori", CodigoCategoria = "0258"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Inmunologia", CodigoCategoria = "0259"},
            new CategoriaCod() { NombreCategoria ="Conductor D Sense Limitació Radi Acció", CodigoCategoria = "0260"},
            new CategoriaCod() { NombreCategoria ="Tècnic/A En Cures Auxiliars D'Infermeria", CodigoCategoria = "0275"},
            new CategoriaCod() { NombreCategoria ="Fisioterapeuta", CodigoCategoria = "0276"},
            new CategoriaCod() { NombreCategoria ="Zelador", CodigoCategoria = "0277"},
            new CategoriaCod() { NombreCategoria ="Odontòlegs De Primària", CodigoCategoria = "0279"},
            new CategoriaCod() { NombreCategoria ="T.E. Radiodiagnòstic", CodigoCategoria = "0280"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er", CodigoCategoria = "0285"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Medicina Interna", CodigoCategoria = "0302"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Reumatologia", CodigoCategoria = "0303"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Neurologia", CodigoCategoria = "0304"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Endocrinologia I Nutrició", CodigoCategoria = "0305"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Aparell Digestiu / Medicina Digestiva", CodigoCategoria = "0306"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Neumologia", CodigoCategoria = "0307"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cardiologia", CodigoCategoria = "0308"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Dermatologia M-Q Y Venereologia", CodigoCategoria = "0310"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Urologia", CodigoCategoria = "0311"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Oftalmologia", CodigoCategoria = "0312"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Otorrinolaringologia", CodigoCategoria = "0313"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Traumatologia I Cirurgia Ortopèdica", CodigoCategoria = "0314"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Obstetricia / Ginecologia", CodigoCategoria = "0315"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Anàlisis Cliniques", CodigoCategoria = "0317"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Farmàcia Clinica", CodigoCategoria = "0350"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Farmàcia Hospitalaria", CodigoCategoria = "0362"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Medicina Preventiva I Salut Publica", CodigoCategoria = "0363"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Anatomia Patològica", CodigoCategoria = "0364"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Radiodiagnòstic", CodigoCategoria = "0365"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Microbiologia I Parasitologia", CodigoCategoria = "0366"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Rehabilitació", CodigoCategoria = "0367"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Medicina Intensiva", CodigoCategoria = "0368"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Pediatria I Àrees Especifiques", CodigoCategoria = "0369"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia General I De L'Aparell Digestiu", CodigoCategoria = "0370"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Anestesiologia / Reanimació", CodigoCategoria = "0371"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Radiofísica Hospitàlaria", CodigoCategoria = "0375"},
            new CategoriaCod() { NombreCategoria ="Terapeuta Ocupacional", CodigoCategoria = "0382"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Rafiofarmàcia", CodigoCategoria = "0400"},
            new CategoriaCod() { NombreCategoria ="Locutor C.I.C.U.", CodigoCategoria = "0402"},
            new CategoriaCod() { NombreCategoria ="Governanta", CodigoCategoria = "0404"},
            new CategoriaCod() { NombreCategoria ="Conductor", CodigoCategoria = "0415"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Neurofisiologia Clínica", CodigoCategoria = "0441"},
            new CategoriaCod() { NombreCategoria ="Veterinari Salut Pública", CodigoCategoria = "0442"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Al.Lergologia", CodigoCategoria = "0443"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Nefrologia", CodigoCategoria = "0444"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Oncologia Medica", CodigoCategoria = "0446"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia Pediàtrica", CodigoCategoria = "0449"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia Cardiovascular", CodigoCategoria = "0450"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia Maxil.Lofacial", CodigoCategoria = "0451"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Neurocirurgia", CodigoCategoria = "0452"},
            new CategoriaCod() { NombreCategoria ="T.E. Anatomia Patològica", CodigoCategoria = "0455"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Oncologia Radioterapica", CodigoCategoria = "0457"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Angiologia I Cirurgia Vascular", CodigoCategoria = "0459"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Geriatria", CodigoCategoria = "0460"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Hematologia I Hemoterapia", CodigoCategoria = "0463"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia Plàstica I Reparadora", CodigoCategoria = "0473"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Medicina Nuclear", CodigoCategoria = "0476"},
            new CategoriaCod() { NombreCategoria ="Pediatria Ap", CodigoCategoria = "0477"},
            new CategoriaCod() { NombreCategoria ="Tècnic De Funció Administrativa", CodigoCategoria = "0483"},
            new CategoriaCod() { NombreCategoria ="Gestió Funció Administrativa", CodigoCategoria = "0484"},
            new CategoriaCod() { NombreCategoria ="F. Esp. Cirurgia Toràcica", CodigoCategoria = "0486"},
            new CategoriaCod() { NombreCategoria ="Enginyer Tècnic", CodigoCategoria = "0516"},
            new CategoriaCod() { NombreCategoria ="Metge Urgència Hospitalaria", CodigoCategoria = "0557"},
            new CategoriaCod() { NombreCategoria ="Higienista Dental", CodigoCategoria = "1001"},
            new CategoriaCod() { NombreCategoria ="Gestió Seguretat Alimentaria I Laboratori", CodigoCategoria = "1014"},
            new CategoriaCod() { NombreCategoria ="Seguretat Alimentària", CodigoCategoria = "1015"},
            new CategoriaCod() { NombreCategoria ="Laboratori Analisis Microbiològiques", CodigoCategoria = "1019"},
            new CategoriaCod() { NombreCategoria ="Laboratori D'Analisi Químic", CodigoCategoria = "1020"},
            new CategoriaCod() { NombreCategoria ="Especialista Salut Pública", CodigoCategoria = "1022"},
            new CategoriaCod() { NombreCategoria ="Farmacèutic Admó Sanitària I Salut Pública", CodigoCategoria = "1024"},
            new CategoriaCod() { NombreCategoria ="Farmacèutic D'Administració Sanitària", CodigoCategoria = "1025"},
            new CategoriaCod() { NombreCategoria ="Metge D'Admó Sanitària I Salut Pública", CodigoCategoria = "1026"},
            new CategoriaCod() { NombreCategoria ="Anàlisis Epidemiològiques I Estadístiques Sa", CodigoCategoria = "1027"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Gestió Sanitària I Salut Pública", CodigoCategoria = "1028"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Especialista Infermeria Familiar I Comunitaria", CodigoCategoria = "1050"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Especialista Infermeria Del Treball", CodigoCategoria = "1051"},
            new CategoriaCod() { NombreCategoria ="Dietista-Nutricionista", CodigoCategoria = "1052"},
            new CategoriaCod() { NombreCategoria ="Òptic-Optometrista", CodigoCategoria = "1053"},
            new CategoriaCod() { NombreCategoria ="Podòleg/Oga", CodigoCategoria = "1054"},
            new CategoriaCod() { NombreCategoria ="Tècnic Especialista En Audologia-Protèsica", CodigoCategoria = "1055"},
            new CategoriaCod() { NombreCategoria ="Tècnic Emergencies Sanitarias", CodigoCategoria = "1056"},
            new CategoriaCod() { NombreCategoria ="Auxiliar De Farmàcia", CodigoCategoria = "1057"},
            new CategoriaCod() { NombreCategoria ="Superior D'Administració General Sanitaria", CodigoCategoria = "1058"},
            new CategoriaCod() { NombreCategoria ="Sanitat Ambiental (A1-S03-04)", CodigoCategoria = "1059"},
            new CategoriaCod() { NombreCategoria ="Metge Administració Sanitària", CodigoCategoria = "1060"},
            new CategoriaCod() { NombreCategoria ="Gestió Administració Sanitària De La Generalitat", CodigoCategoria = "1061"},
            new CategoriaCod() { NombreCategoria ="Superior Gestió Sanitat Ambiental (A2-S03-03)", CodigoCategoria = "1062"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Samu", CodigoCategoria = "2000"},
            new CategoriaCod() { NombreCategoria ="Metge Samu", CodigoCategoria = "2001"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Especialista En Infermeria De Salut Mental", CodigoCategoria = "3001"},
            new CategoriaCod() { NombreCategoria ="Facultatiu Especilista En Medicina Del Treball", CodigoCategoria = "3002"},
            new CategoriaCod() { NombreCategoria ="Logopeda", CodigoCategoria = "3003"},
            new CategoriaCod() { NombreCategoria ="Tècnic Intermedi En Prevenció De Riscos Laborals", CodigoCategoria = "3004"},
            new CategoriaCod() { NombreCategoria ="Tècnic Superior En Higiene Del Treball", CodigoCategoria = "3005"},
            new CategoriaCod() { NombreCategoria ="Tècnic Superior En Seguretat En El Treball", CodigoCategoria = "3006"},
            new CategoriaCod() { NombreCategoria ="Tècnic Superior En Psicosociologia I Ergonomia En El Treball", CodigoCategoria = "3007"},
            new CategoriaCod() { NombreCategoria ="Tècnic Especialista En Documentació Sanitaria", CodigoCategoria = "3008"},
            new CategoriaCod() { NombreCategoria ="Infermera/Er Inspector", CodigoCategoria = "3100"},
            new CategoriaCod() { NombreCategoria ="Fac. Esp. Psicología Clínica", CodigoCategoria = "3101"},
            new CategoriaCod() { NombreCategoria ="Farmacèutic Inspector", CodigoCategoria = "3102"},
            new CategoriaCod() { NombreCategoria ="Inspector Metge", CodigoCategoria = "3103"},
            new CategoriaCod() { NombreCategoria ="Infermer/A Especialista Pediatria", CodigoCategoria = "3200"},
            new CategoriaCod() { NombreCategoria ="Infermer/A/Er Especilista En Infermeria Geriàtrica", CodigoCategoria = "3201"},
            new CategoriaCod() { NombreCategoria ="Periodista", CodigoCategoria = "3202"},
            new CategoriaCod() { NombreCategoria ="Operador/A Cambra Hiperbàrica", CodigoCategoria = "3203"},
            new CategoriaCod() { NombreCategoria ="Enginyer/A Superior", CodigoCategoria = "3204"},

        };

    }
}
